package com.lp.mapper;

import com.lp.pojo.LpText;
import com.lp.pojo.LpTextExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LpTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    long countByExample(LpTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int deleteByExample(LpTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int insert(LpText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int insertSelective(LpText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    List<LpText> selectByExample(LpTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    LpText selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LpText record, @Param("example") LpTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LpText record, @Param("example") LpTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LpText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_text
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LpText record);
}